### ISSUE TITLE
Don't show the lightdm screen

### ISSUE THREAD

**Issue by eailfly** [jqln-0/Bevel#1]
Hi, I do the install follow your setup
1.Clone this repository into /usr/share/lightdm-webkit/themes/bevel
2.Set the theme in /etc/lightdm/lightdm-webkit-greeter.conf
But when I restart I only get this
![1069450568](https://cloud.githubusercontent.com/assets/3424220/21124270/d28bbeb2-c118-11e6-8d2f-081b3b261463.jpg)
A black screen whith mouse curse
I'm use Arch , did I do something wrong? 
Is there any log file so I can find what's worng?

**Comment by jqln-0** [comment]
I believe lightdm does dump some useful logs somewhere... possibly just in /var/log? I don't recall exactly. Although before digging about for logs, a good first step would be trying to isolate exactly where the problem is. Can you get lightdm working with other greeters? If you can, can you get the webkit greeter working with the default theme? More than likely the problem you're encountering is nothing to do with this theme in particular.

You may also have better luck finding help by posting on Arch forums or Reddit. Filing an issue against a GitHub repo is for when you've found a bug or have a feature request, not for when you need general technical support.

**Comment by eailfly** [comment]
lightdm is work fine on lightdm-webkit with the default theme antergos.
I'll post the question on Arch forum. Thanks.
